### ISSUE TITLE
Reformular CMS

### ISSUE THREAD

**Issue by genezysg** [vtex/formula-vtex#1]
Equipe: Content is king

@amoreira , @leandrooriente 

Tema: Criação e publicação de conteúdo online da VTEX (Blog, Site, Docs)
Descrição: Vamos ter uma plataforma de publicação ágil e que todo mundo pode participar!

**Comment by leandrooriente** [comment]
To fora.
Sou da equipe LAN House IN House agora

**Comment by geraldothomaz** [comment]
Esse projeto não é o nosso portal mega drag and drop? Ele não vai resolver esse problema?

**Comment by firstdoit** [comment]
Não vai rolar por causa do escopo. Decidimos que fazer um blog decente no Storefront demandará mais tempo, vai ser feito no fluxo de trabalho normal.
