### ISSUE TITLE
LAN House IN House

### ISSUE THREAD

**Issue by leandrooriente** [vtex/formula-vtex#10]
### Meta:

6 baias, 6 computadores, dois trios, um servidor de Counter Strike 1.6

Lembrando os bons e velhos tempos de madrugadão.
### Tasks:
- Remover entulho ou realocar na sala.
- Configurar 6 desktops velhos com Windows 7, Counter Strike, Age of Empires, GTA...
- Ajustar uma rede local para não depender de internet.
### Utopia
- Um frigobar com cervejas e energéticos _infinitos e gratuitos_.
- 10 Desktops.
- Nenhum entulho.
- Decoração underground.

**Comment by leandrooriente** [comment]
Time vencedor aqui:
@gugiserman, @felipecastrosm, @NicolasAbreu, @leandrooriente e Felipe França

**Comment by leandrooriente** [comment]
Melhor formula VTEX

**Comment by ohmyguigs** [comment]
Melhor @leandrooriente
