### ISSUE TITLE
Venda offline com pedido serializado em QRCode 

### ISSUE THREAD

**Issue by firstdoit** [vtex/formula-vtex#11]
Existem duas partes, usuário e vending machine. Vending machine funciona offline com sincronização eventual. Pode ser um iPad, à princípio, rodando um SPA com infos no localStorage.

1 - Usuário faz pedido online via smart checkout
2 - Order placed e email contém QRCode com um JSON especificando todo o pedido + chave de autenticação
3 - Usuário apresenta QRCode a vending machine que consegue validar chave offline + mostrar pedido (já tem todas as infos offline)
4 - Vending eventualmente confirma entrega para servidor

**Comment by firstdoit** [comment]
@brenoc @amoreira @brunoabreu @dfosco partiu?

**Comment by firstdoit** [comment]
@gabrielarrais falou que quer participar

**Comment by dfosco** [comment]
@firstdoit Vai rolar mesmo esse grupo?

**Comment by firstdoit** [comment]
Eu e @brenoc estamos confirmados, aguardo confirmação dos outros. @brunoabreu falou que quer entender melhor o problema!

**Comment by dfosco** [comment]
Partiu! Só vou ter que abandonar meu projeto atual, haha 😁

@ribeirofelix... for the watch

**Comment by brenoc** [comment]
@firstdoit to mega atolado com o mestrado, eu não vou poder ir no sábado, tenho que fazer trabalho de uma matéria e lista de exercícios de outra

**Comment by firstdoit** [comment]
Tudo bem :) A gente termina na sexta e bebe no sábado. rs

**Comment by klzns** [comment]
😲 😲 😲
