### ISSUE TITLE
Colossus

### ISSUE THREAD

**Issue by danielblando** [vtex/formula-vtex#12]
Projeto:

   Criar um ambiente de Plataforma as a Service. A proposta é criar um cadastro de endpoint e upload de aplicacao e nossa infra fica responsavel em disponibilizar e manter a rota cadastrada.

Participantes:

   @danielblando
   @alanprot

**Comment by firstdoit** [comment]
Falem com o @vmattos!!! :octocat:

**Comment by Caldas** [comment]
Muito maneiro. Vai usar aquele banco novo @alanprot?

-----Mensagem Original-----
De: "Daniel Blando" <notifications@github.com>
Enviada em: ‎18/‎06/‎2015 13:27
Para: "vtex/formula-vtex" <formula-vtex@noreply.github.com>
Assunto: [formula-vtex] Refugio (#12)

Projeto:
Criar um ambiente de Plataforma as a Service. A proposta é criar um cadastro de endpoint e upload de aplicacao e nossa infra fica responsavel em disponibilizar e manter a rota cadastrada.
Participantes:
@danielblando
@alanprot
