### ISSUE TITLE
DuckTales

### ISSUE THREAD

**Issue by ghost** [vtex/formula-vtex#13]
Vamos embarcar na aventura de contabilizar os custos da nossa plataforma.

JUNTOS EM BUSCA DA MOEDINHA DA SORTE NÚMERO 1 !

Participantes:

@aabreur 
@carlosmonteiro 
@Rodrigo-Medeiros-Vtex

**Comment by Rodrigo-Medeiros-Vtex** [comment]
@carlosmonteiro 
@aabreur
