### ISSUE TITLE
VTEXNow

### ISSUE THREAD

**Issue by genezysg** [vtex/formula-vtex#6]
**Team:** @Caldas & @Abinader & @vmattos & @alejandro-osorio & @gugiserman 

**Proposta:** Projeto para criação de uma Home interativa e mais informativa.

**Comment by Caldas** [comment]
Para que o projeto possa ter início, meio e fim durante o tempo proposto para o formúla VTEX o projeto foi ajustado para ter como proposta a criação de uma nova Home para os usuários que acessarem **/admin**

**Comment by Caldas** [comment]
O projeto vai precisar contar com 2 frentes:

** Integração de "informações"

* Integrar as notícias que hoje aparecem no **/admin**:
![image](https://cloud.githubusercontent.com/assets/938045/8145823/0356ccec-11ef-11e5-88fd-c24e5489a909.png)
* Integrar **DO**
* Integrar **Release**
* Integrar informações vindas do **Data Cluster**

** Criação de componentes para exibição de dados da loja, proveniente do **Data Cluster**
